# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='hpicture',
            field=models.ImageField(default='aaa.jpeg', upload_to='heros/'),
            preserve_default=False,
        ),
    ]
