# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171104_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.BooleanField()),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('level', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage(location='C:/Users/wangz/Desktop/kingsite/static/head/'))),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_GET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='diamond',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='stamps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/wangz/Desktop/kingsite/static/media/'), upload_to=''),
        ),
        migrations.AddField(
            model_name='user_get',
            name='heros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Hero'),
        ),
        migrations.AddField(
            model_name='user_get',
            name='skins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Skin'),
        ),
        migrations.AddField(
            model_name='user_get',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
