# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171104_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='diamond',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='money',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='stamps',
        ),
        migrations.AddField(
            model_name='user',
            name='diamond',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stamps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
