# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:05
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171104_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/wangz/Desktop/kingsite/static/head/'), upload_to=''),
        ),
    ]
