# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc',
            field=models.CharField(default='商品', max_length=200, verbose_name='描述'),
        ),
    ]
