# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=datetime.datetime(2017, 9, 20, 9, 32, 7, 880432, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
