# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_heroinfo_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hgender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hlaunch_date',
            new_name='launch_date',
        ),
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skininfo',
            old_name='scontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='skininfo',
            old_name='shero',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='skininfo',
            old_name='sname',
            new_name='name',
        ),
    ]
