# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(db_column='uname', max_length=20)),
                ('upwd', models.CharField(db_column='upwd', max_length=64)),
            ],
        ),
    ]
