# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(db_column='name', max_length=20, unique=True),
        ),
    ]
